-- ============================================================
-- Seed genres + substyles iš constants.ts (2026-04-25)
-- ============================================================
-- Tikslas: kad wiki_worker matchintų Wikidata P136 labels prieš
-- esamus DB pavadinimus, ne kurtų random raw eilutes.

BEGIN;

-- 1. Cleanup any links + existing data (po wipe paprastai jau tuščia)
DELETE FROM public.artist_substyles;
DELETE FROM public.artist_genres;
DELETE FROM public.substyles;
DELETE FROM public.genres;

-- 2. 8 main genres
INSERT INTO public.genres (name) VALUES
  ('Alternatyvioji muzika'),
  ('Elektroninė, šokių muzika'),
  ('o muzika'),
  ('Kitų stilių muzika'),
  ('Pop, R&B muzika'),
  ('Rimtoji muzika'),
  ('Roko muzika'),
  ('Sunkioji muzika');

-- 3. Substyles (538 viso) — flat table, name + slug
INSERT INTO public.substyles (name, slug) VALUES
  ('2 step', '2-step'),
  ('Acid rock', 'acid-rock'),
  ('Acoustic', 'acoustic'),
  ('Aggrotech', 'aggrotech'),
  ('Alternative', 'alternative'),
  ('Alternative dance', 'alternative-dance'),
  ('Alternative hip hop', 'alternative-hip-hop'),
  ('Alternative pop', 'alternative-pop'),
  ('Alternative rap', 'alternative-rap'),
  ('Ambient', 'ambient'),
  ('Apocalyptic folk', 'apocalyptic-folk'),
  ('Avant-garde', 'avant-garde'),
  ('Avant-garde rock', 'avant-garde-rock'),
  ('Bass', 'bass'),
  ('Bossa nova', 'bossa-nova'),
  ('Cabaret', 'cabaret'),
  ('Celtic', 'celtic'),
  ('Celtic punk', 'celtic-punk'),
  ('Dainuojamoji poezija', 'dainuojamoji-poezija'),
  ('Dark ambient', 'dark-ambient'),
  ('Dark Cabaret', 'dark-cabaret'),
  ('Dark electro', 'dark-electro'),
  ('Dark pop', 'dark-pop'),
  ('Dark Wave', 'dark-wave'),
  ('Desert rock', 'desert-rock'),
  ('Downtempo', 'downtempo'),
  ('Drone', 'drone'),
  ('Dub', 'dub'),
  ('Dubstep', 'dubstep'),
  ('Easy listening', 'easy-listening'),
  ('EBM', 'ebm'),
  ('Electro industrial', 'electro-industrial'),
  ('Electro rock', 'electro-rock'),
  ('Emo', 'emo'),
  ('Experimental', 'experimental'),
  ('Experimental rock', 'experimental-rock'),
  ('Folk', 'folk'),
  ('Folk punk', 'folk-punk'),
  ('Folk rock', 'folk-rock'),
  ('Freak folk', 'freak-folk'),
  ('Funk', 'funk'),
  ('Future jazz', 'future-jazz'),
  ('Futurepop', 'futurepop'),
  ('Glam rock', 'glam-rock'),
  ('Glitch', 'glitch'),
  ('Grime', 'grime'),
  ('Grunge', 'grunge'),
  ('Hardcore punk', 'hardcore-punk'),
  ('Harsh Electro', 'harsh-electro'),
  ('Horror punk', 'horror-punk'),
  ('IDM', 'idm'),
  ('Indie', 'indie'),
  ('Indie folk', 'indie-folk'),
  ('Industrial', 'industrial'),
  ('Instrumental pop', 'instrumental-pop'),
  ('J-rock', 'j-rock'),
  ('Kita', 'kita'),
  ('Krautrock', 'krautrock'),
  ('Lo-fi', 'lo-fi'),
  ('Madchester', 'madchester'),
  ('Martial', 'martial'),
  ('Martial industrial/military pop', 'martial-industrial-military-pop'),
  ('Melodic hardcore', 'melodic-hardcore'),
  ('Minimalistic', 'minimalistic'),
  ('Neo soul', 'neo-soul'),
  ('Neofolk', 'neofolk'),
  ('New Age', 'new-age'),
  ('Noise', 'noise'),
  ('Pop punk', 'pop-punk'),
  ('Post grunge', 'post-grunge'),
  ('Post hardcore', 'post-hardcore'),
  ('Post industrial', 'post-industrial'),
  ('Post punk', 'post-punk'),
  ('Post rock', 'post-rock'),
  ('Power electronics', 'power-electronics'),
  ('Power noise', 'power-noise'),
  ('Progressive rock', 'progressive-rock'),
  ('Psych folk', 'psych-folk'),
  ('Psychedelic pop', 'psychedelic-pop'),
  ('Psychedelic soul', 'psychedelic-soul'),
  ('Punk rock', 'punk-rock'),
  ('Rap metal', 'rap-metal'),
  ('Rapcore', 'rapcore'),
  ('Rhythmic Noise', 'rhythmic-noise'),
  ('Roots music', 'roots-music'),
  ('Screamo', 'screamo'),
  ('Shoegazing', 'shoegazing'),
  ('Ska', 'ska'),
  ('Ska punk', 'ska-punk'),
  ('Spoken word', 'spoken-word'),
  ('Steampunk', 'steampunk'),
  ('Stoner rock', 'stoner-rock'),
  ('Surf rock', 'surf-rock'),
  ('Trip hop', 'trip-hop'),
  ('Turntablism', 'turntablism'),
  ('UK garage', 'uk-garage'),
  ('World', 'world'),
  ('Acid house', 'acid-house'),
  ('Acid jazz', 'acid-jazz'),
  ('Acid techno', 'acid-techno'),
  ('Acid trance', 'acid-trance'),
  ('Ambient house', 'ambient-house'),
  ('Ambient techno', 'ambient-techno'),
  ('Baile funk', 'baile-funk'),
  ('Balearic beat', 'balearic-beat'),
  ('Balearic house', 'balearic-house'),
  ('Big beat', 'big-beat'),
  ('Brazilian Bass', 'brazilian-bass'),
  ('Break', 'break'),
  ('Breakbeat', 'breakbeat'),
  ('Breakcore', 'breakcore'),
  ('Breakdance', 'breakdance'),
  ('Breaks', 'breaks'),
  ('Broken beat', 'broken-beat'),
  ('Chill-out', 'chill-out'),
  ('Chillwave', 'chillwave'),
  ('Chiptune', 'chiptune'),
  ('Club', 'club'),
  ('Dance', 'dance'),
  ('Dance punk', 'dance-punk'),
  ('Deep house', 'deep-house'),
  ('Detroit techno', 'detroit-techno'),
  ('Disco', 'disco'),
  ('Downbeat', 'downbeat'),
  ('Dream house', 'dream-house'),
  ('Drill & Bass', 'drill-bass'),
  ('Drum & Bass', 'drum-bass'),
  ('Dubstyle', 'dubstyle'),
  ('Early trance', 'early-trance'),
  ('Electro', 'electro'),
  ('Electro funk', 'electro-funk'),
  ('Electro hop', 'electro-hop'),
  ('Electro house', 'electro-house'),
  ('Electro pop', 'electro-pop'),
  ('Electro techno', 'electro-techno'),
  ('Electroclash', 'electroclash'),
  ('Electronica', 'electronica'),
  ('Ethnic electronica', 'ethnic-electronica'),
  ('Euro disco', 'euro-disco'),
  ('Euro house', 'euro-house'),
  ('Euro trance', 'euro-trance'),
  ('Eurobeat', 'eurobeat'),
  ('Eurodance', 'eurodance'),
  ('Experimental techno', 'experimental-techno'),
  ('Fidget house', 'fidget-house'),
  ('Folktronica', 'folktronica'),
  ('French house', 'french-house'),
  ('Funktronica', 'funktronica'),
  ('Funky breaks', 'funky-breaks'),
  ('Funky house', 'funky-house'),
  ('Gabber', 'gabber'),
  ('Garage', 'garage'),
  ('Goa trance', 'goa-trance'),
  ('Happy hardcore', 'happy-hardcore'),
  ('Hard dance', 'hard-dance'),
  ('Hard house', 'hard-house'),
  ('Hard trance', 'hard-trance'),
  ('Hardcore Techno', 'hardcore-techno'),
  ('Hardstyle', 'hardstyle'),
  ('Hi-NRG', 'hi-nrg'),
  ('House', 'house'),
  ('Illbient', 'illbient'),
  ('Indie electronic', 'indie-electronic'),
  ('Industrial dance', 'industrial-dance'),
  ('Italo Dance', 'italo-dance'),
  ('Italo disco', 'italo-disco'),
  ('Jumpstyle', 'jumpstyle'),
  ('Jungle', 'jungle'),
  ('Latin dance', 'latin-dance'),
  ('Left-field house', 'left-field-house'),
  ('Lento Violento', 'lento-violento'),
  ('Liquid Funk', 'liquid-funk'),
  ('Mashup', 'mashup'),
  ('Microsound', 'microsound'),
  ('Minimal', 'minimal'),
  ('Neo electro', 'neo-electro'),
  ('Neotango', 'neotango'),
  ('New beat', 'new-beat'),
  ('New rave', 'new-rave'),
  ('Nu breaks', 'nu-breaks'),
  ('Nu disco', 'nu-disco'),
  ('Old School Jungle', 'old-school-jungle'),
  ('Polka', 'polka'),
  ('Post disco', 'post-disco'),
  ('Progressive house', 'progressive-house'),
  ('Progressive trance', 'progressive-trance'),
  ('Psy trance', 'psy-trance'),
  ('Psybient', 'psybient'),
  ('Rave', 'rave'),
  ('Samba', 'samba'),
  ('Symphonic techno', 'symphonic-techno'),
  ('Synthpunk', 'synthpunk'),
  ('Tango', 'tango'),
  ('Tech house', 'tech-house'),
  ('Tech-trance', 'tech-trance'),
  ('Techno', 'techno'),
  ('Trance', 'trance'),
  ('Tribal', 'tribal'),
  ('Uplifting trance', 'uplifting-trance'),
  ('Vocal trance', 'vocal-trance'),
  ('Witch house', 'witch-house'),
  ('Bounce', 'bounce'),
  ('Comedy hip hop', 'comedy-hip-hop'),
  ('Country rap', 'country-rap'),
  ('Crunk', 'crunk'),
  ('Crunkcore', 'crunkcore'),
  ('Dirty rap', 'dirty-rap'),
  ('East Coast hip hop', 'east-coast-hip-hop'),
  ('G-Funk', 'g-funk'),
  ('Gangsta rap', 'gangsta-rap'),
  ('Golden age', 'golden-age'),
  ('Hardcore hip hop', 'hardcore-hip-hop'),
  ('Hip hop', 'hip-hop'),
  ('Hip hop soul', 'hip-hop-soul'),
  ('Horrorcore', 'horrorcore'),
  ('Japanese hip hop', 'japanese-hip-hop'),
  ('Jazz rap', 'jazz-rap'),
  ('Latin rap', 'latin-rap'),
  ('Midwest hip hop', 'midwest-hip-hop'),
  ('Old School Hip Hop', 'old-school-hip-hop'),
  ('Political rap', 'political-rap'),
  ('Pop rap', 'pop-rap'),
  ('Ragga', 'ragga'),
  ('Rap', 'rap'),
  ('Rap rock', 'rap-rock'),
  ('Reggaeton', 'reggaeton'),
  ('Snap', 'snap'),
  ('Southern hip hop', 'southern-hip-hop'),
  ('Thug rap', 'thug-rap'),
  ('UK hip hop', 'uk-hip-hop'),
  ('Underground hip hop', 'underground-hip-hop'),
  ('West Coast hip hop', 'west-coast-hip-hop'),
  ('2 Tone', '2-tone'),
  ('A cappella', 'a-cappella'),
  ('Abstract', 'abstract'),
  ('Afrobeat', 'afrobeat'),
  ('Alternative country', 'alternative-country'),
  ('Anapus', 'anapus'),
  ('Anasheed', 'anasheed'),
  ('Anti Folk', 'anti-folk'),
  ('Axe', 'axe'),
  ('Bachata', 'bachata'),
  ('Beatbox', 'beatbox'),
  ('Bhangra', 'bhangra'),
  ('Bluegrass', 'bluegrass'),
  ('Brazilian', 'brazilian'),
  ('Cajun', 'cajun'),
  ('Celtic fusion', 'celtic-fusion'),
  ('Cha-cha-cha', 'cha-cha-cha'),
  ('Choir', 'choir'),
  ('Comedy', 'comedy'),
  ('Compas', 'compas'),
  ('Congolese', 'congolese'),
  ('Country', 'country'),
  ('Cyberpunk', 'cyberpunk'),
  ('Dancehall', 'dancehall'),
  ('Digital hardcore', 'digital-hardcore'),
  ('Electro Swing', 'electro-swing'),
  ('Enka', 'enka'),
  ('Ethnic', 'ethnic'),
  ('Ethnic fusion', 'ethnic-fusion'),
  ('Filmų muzika', 'filmu-muzika'),
  ('Fingerstyle', 'fingerstyle'),
  ('Flamenco', 'flamenco'),
  ('Gypsy', 'gypsy'),
  ('Hamd', 'hamd'),
  ('Hawaiian', 'hawaiian'),
  ('Hindu', 'hindu'),
  ('Humppa', 'humppa'),
  ('Laïko', 'la-ko'),
  ('Latin', 'latin'),
  ('Mambo', 'mambo'),
  ('March', 'march'),
  ('Mbalax', 'mbalax'),
  ('MPB', 'mpb'),
  ('Neo medieval', 'neo-medieval'),
  ('Nueva trova', 'nueva-trova'),
  ('Outlaw country', 'outlaw-country'),
  ('Pagode', 'pagode'),
  ('Parody', 'parody'),
  ('Ranchera', 'ranchera'),
  ('Reggae', 'reggae'),
  ('Reggae fusion', 'reggae-fusion'),
  ('Rocksteady', 'rocksteady'),
  ('Roots reggae', 'roots-reggae'),
  ('Salsa', 'salsa'),
  ('Sertanejo', 'sertanejo'),
  ('Shibuya-kei', 'shibuya-kei'),
  ('Son', 'son'),
  ('Space', 'space'),
  ('Swing revival', 'swing-revival'),
  ('Tejano', 'tejano'),
  ('Third wave ska', 'third-wave-ska'),
  ('Trailer music', 'trailer-music'),
  ('Tropicalia', 'tropicalia'),
  ('Vocaloid', 'vocaloid'),
  ('World beat', 'world-beat'),
  ('Ambient pop', 'ambient-pop'),
  ('Arabic pop', 'arabic-pop'),
  ('Art pop', 'art-pop'),
  ('Balkan pop', 'balkan-pop'),
  ('Ballad', 'ballad'),
  ('Baroque pop', 'baroque-pop'),
  ('Blue-eyed soul', 'blue-eyed-soul'),
  ('Bolero', 'bolero'),
  ('Boogaloo', 'boogaloo'),
  ('Brown-eyed soul', 'brown-eyed-soul'),
  ('Chanson', 'chanson'),
  ('Chicago soul', 'chicago-soul'),
  ('Children', 'children'),
  ('Christmas music', 'christmas-music'),
  ('Contemporary Christian', 'contemporary-christian'),
  ('Country pop', 'country-pop'),
  ('Cumbia', 'cumbia'),
  ('Dance pop', 'dance-pop'),
  ('Doo wop', 'doo-wop'),
  ('Europop', 'europop'),
  ('French pop', 'french-pop'),
  ('Guajira', 'guajira'),
  ('Indipop', 'indipop'),
  ('J pop', 'j-pop'),
  ('K-pop', 'k-pop'),
  ('Latin pop', 'latin-pop'),
  ('Lounge music', 'lounge-music'),
  ('LT estrada', 'lt-estrada'),
  ('Merengue', 'merengue'),
  ('New jack swing', 'new-jack-swing'),
  ('New romanticism', 'new-romanticism'),
  ('Operatic pop', 'operatic-pop'),
  ('Philadelphia soul', 'philadelphia-soul'),
  ('Pop', 'pop'),
  ('Pop rock', 'pop-rock'),
  ('Quiet storm', 'quiet-storm'),
  ('R&B', 'r-b'),
  ('Russian pop', 'russian-pop'),
  ('Schlager', 'schlager'),
  ('Sophisti pop', 'sophisti-pop'),
  ('Soul', 'soul'),
  ('Southern soul', 'southern-soul'),
  ('Sunshine pop', 'sunshine-pop'),
  ('Synthpop', 'synthpop'),
  ('Teen pop', 'teen-pop'),
  ('Traditional pop', 'traditional-pop'),
  ('Tropical', 'tropical'),
  ('Urban', 'urban'),
  ('Vocal pop', 'vocal-pop'),
  ('Wonky pop', 'wonky-pop'),
  ('Adult contemporary', 'adult-contemporary'),
  ('Afro-Cuban jazz', 'afro-cuban-jazz'),
  ('Avant-garde jazz', 'avant-garde-jazz'),
  ('Bebop', 'bebop'),
  ('Big band', 'big-band'),
  ('Blues', 'blues'),
  ('Boogie woogie', 'boogie-woogie'),
  ('British blues', 'british-blues'),
  ('Chicago blues', 'chicago-blues'),
  ('Classical', 'classical'),
  ('Classical crossover', 'classical-crossover'),
  ('Cool jazz', 'cool-jazz'),
  ('Country blues', 'country-blues'),
  ('Crossover jazz', 'crossover-jazz'),
  ('Cubop', 'cubop'),
  ('Delta blues', 'delta-blues'),
  ('Dixieland', 'dixieland'),
  ('Electric blues', 'electric-blues'),
  ('Free improvisation', 'free-improvisation'),
  ('Free jazz', 'free-jazz'),
  ('Gospel', 'gospel'),
  ('Gospel blues', 'gospel-blues'),
  ('Gregorian', 'gregorian'),
  ('Hard bop', 'hard-bop'),
  ('Instrumental', 'instrumental'),
  ('Jazz', 'jazz'),
  ('Jazz blues', 'jazz-blues'),
  ('Jazz funk', 'jazz-funk'),
  ('Jazz fusion', 'jazz-fusion'),
  ('Jazz Hop', 'jazz-hop'),
  ('Jazz rock', 'jazz-rock'),
  ('Jazzcore', 'jazzcore'),
  ('Jazzstep', 'jazzstep'),
  ('Jive', 'jive'),
  ('Latin jazz', 'latin-jazz'),
  ('Modal jazz', 'modal-jazz'),
  ('Modern classical', 'modern-classical'),
  ('Neo classical', 'neo-classical'),
  ('New classical', 'new-classical'),
  ('Nu jazz', 'nu-jazz'),
  ('Opera', 'opera'),
  ('Piano blues', 'piano-blues'),
  ('Post bop', 'post-bop'),
  ('Post jazz', 'post-jazz'),
  ('Ragtime', 'ragtime'),
  ('Smooth jazz', 'smooth-jazz'),
  ('Soul blues', 'soul-blues'),
  ('Soul jazz', 'soul-jazz'),
  ('Space age', 'space-age'),
  ('Stride', 'stride'),
  ('Swing', 'swing'),
  ('Talking blues', 'talking-blues'),
  ('Texas blues', 'texas-blues'),
  ('Third stream', 'third-stream'),
  ('Torch songs', 'torch-songs'),
  ('Vocal jazz', 'vocal-jazz'),
  ('Acid / Psychedelic Blues', 'acid-psychedelic-blues'),
  ('Acoustic rock', 'acoustic-rock'),
  ('Alternative rock', 'alternative-rock'),
  ('Americana', 'americana'),
  ('Anarcho punk', 'anarcho-punk'),
  ('Arena rock', 'arena-rock'),
  ('Art punk', 'art-punk'),
  ('Art rock', 'art-rock'),
  ('Atmospheric rock', 'atmospheric-rock'),
  ('Beat', 'beat'),
  ('Blues rock', 'blues-rock'),
  ('Boogie rock', 'boogie-rock'),
  ('Britpop', 'britpop'),
  ('Cello rock', 'cello-rock'),
  ('Celtic rock', 'celtic-rock'),
  ('Chicano rock', 'chicano-rock'),
  ('Christian rock', 'christian-rock'),
  ('Classic rock', 'classic-rock'),
  ('College rock', 'college-rock'),
  ('Comedy rock', 'comedy-rock'),
  ('Country rock', 'country-rock'),
  ('Death rock', 'death-rock'),
  ('Dream pop', 'dream-pop'),
  ('Electronic rock', 'electronic-rock'),
  ('Ethereal wave', 'ethereal-wave'),
  ('Funk rock', 'funk-rock'),
  ('Garage rock', 'garage-rock'),
  ('Garage rock revival', 'garage-rock-revival'),
  ('Geek rock', 'geek-rock'),
  ('German rock', 'german-rock'),
  ('Glam punk', 'glam-punk'),
  ('Gothabilly', 'gothabilly'),
  ('Gothic rock', 'gothic-rock'),
  ('Gypsy punk', 'gypsy-punk'),
  ('Hard rock', 'hard-rock'),
  ('Heartland rock', 'heartland-rock'),
  ('Indie pop', 'indie-pop'),
  ('Indie rock', 'indie-rock'),
  ('Industrial rock', 'industrial-rock'),
  ('Instrumental rock', 'instrumental-rock'),
  ('Italian progressive rock', 'italian-progressive-rock'),
  ('Jam band', 'jam-band'),
  ('Jangle pop', 'jangle-pop'),
  ('Latin rock', 'latin-rock'),
  ('LT old rock', 'lt-old-rock'),
  ('Math rock', 'math-rock'),
  ('Medieval rock', 'medieval-rock'),
  ('Mod Revival', 'mod-revival'),
  ('Neo progressive rock', 'neo-progressive-rock'),
  ('Neo psychedelia', 'neo-psychedelia'),
  ('Neue Deutsche Härte', 'neue-deutsche-h-rte'),
  ('Neue Deutsche Welle', 'neue-deutsche-welle'),
  ('New prog', 'new-prog'),
  ('New Wave', 'new-wave'),
  ('Noise pop', 'noise-pop'),
  ('Noise rock', 'noise-rock'),
  ('Occult rock', 'occult-rock'),
  ('Oi!', 'oi'),
  ('Pagan rock', 'pagan-rock'),
  ('Piano rock', 'piano-rock'),
  ('Post britpop', 'post-britpop'),
  ('Post punk revival', 'post-punk-revival'),
  ('Powerpop', 'powerpop'),
  ('Protopunk', 'protopunk'),
  ('Psychedelic folk', 'psychedelic-folk'),
  ('Psychedelic rock', 'psychedelic-rock'),
  ('Psychobilly', 'psychobilly'),
  ('Pub rock', 'pub-rock'),
  ('Punk blues', 'punk-blues'),
  ('Queercore', 'queercore'),
  ('Raga rock', 'raga-rock'),
  ('Riot grrrl', 'riot-grrrl'),
  ('Rock', 'rock'),
  ('Rock noir', 'rock-noir'),
  ('Rock\''n\''roll', 'rock-n-roll'),
  ('Rockabilly', 'rockabilly'),
  ('Roots rock', 'roots-rock'),
  ('Russian rock', 'russian-rock'),
  ('Sadcore', 'sadcore'),
  ('Shock rock', 'shock-rock'),
  ('Ska-core', 'ska-core'),
  ('Skate punk', 'skate-punk'),
  ('Soft rock', 'soft-rock'),
  ('Southern rock', 'southern-rock'),
  ('Space rock', 'space-rock'),
  ('Street punk', 'street-punk'),
  ('Symphonic rock', 'symphonic-rock'),
  ('Synthrock', 'synthrock'),
  ('Trip rock', 'trip-rock'),
  ('Visual Kei', 'visual-kei'),
  ('Alternative metal', 'alternative-metal'),
  ('Avant-garde metal', 'avant-garde-metal'),
  ('Black metal', 'black-metal'),
  ('Cello metal', 'cello-metal'),
  ('Celtic metal', 'celtic-metal'),
  ('Christian metal', 'christian-metal'),
  ('Crossover thrash', 'crossover-thrash'),
  ('Death metal', 'death-metal'),
  ('Death\''n\''roll', 'death-n-roll'),
  ('Death/doom', 'death-doom'),
  ('Deathcore', 'deathcore'),
  ('Deathgrind', 'deathgrind'),
  ('Doom metal', 'doom-metal'),
  ('Extreme metal', 'extreme-metal'),
  ('Flamenco metal', 'flamenco-metal'),
  ('Folk metal', 'folk-metal'),
  ('Funeral doom', 'funeral-doom'),
  ('Funk metal', 'funk-metal'),
  ('Glam metal', 'glam-metal'),
  ('Gothic metal', 'gothic-metal'),
  ('Grindcore', 'grindcore'),
  ('Groove metal', 'groove-metal'),
  ('Heavy metal', 'heavy-metal'),
  ('Industrial metal', 'industrial-metal'),
  ('Mathcore', 'mathcore'),
  ('Medieval metal', 'medieval-metal'),
  ('Melodic death metal', 'melodic-death-metal'),
  ('Metal', 'metal'),
  ('Metalcore', 'metalcore'),
  ('Neo-classical metal', 'neo-classical-metal'),
  ('NSBM', 'nsbm'),
  ('Nu metal', 'nu-metal'),
  ('Pagan metal', 'pagan-metal'),
  ('Post metal', 'post-metal'),
  ('Power metal', 'power-metal'),
  ('Progressive metal', 'progressive-metal'),
  ('Punk metal', 'punk-metal'),
  ('Sludge metal', 'sludge-metal'),
  ('Southern metal', 'southern-metal'),
  ('Speed metal', 'speed-metal'),
  ('Symphonic metal', 'symphonic-metal'),
  ('Technical death metal', 'technical-death-metal'),
  ('Thrash metal', 'thrash-metal'),
  ('Thrashcore', 'thrashcore'),
  ('Viking metal', 'viking-metal');

COMMIT;