-- 20260614c_collections_expand.sql
-- Naujos dainu kolekcijos is GSC paklausos + SERP chips.
insert into public.collections (slug,kind,title,emoji,meta_title,description,intro,grp,sort,is_active) values
('patriotines-dainos','song','Patriotinės dainos','🇱🇹','Patriotinės dainos — Lietuvos himnai ir dainos apie Tėvynę | music.lt','Patriotinės lietuviškos dainos: kūriniai apie Tėvynę, laisvę ir Lietuvą. Dainos Vasario 16-ajai, Kovo 11-ajai ir valstybės šventėms.','Patriotinė daina sujungia tautą. Šiame rinkinyje — gražiausios lietuviškos dainos apie Tėvynę, laisvę ir Lietuvą: nuo iškilmingų himnų iki šiuolaikinių kūrinių. Tinka Vasario 16-ajai, Kovo 11-ajai, Liepos 6-ajai ir kitoms valstybės šventėms.','tema',13,true),
('visu-laiku-geriausios-lietuviskos','song','Visų laikų geriausios lietuviškos dainos','🏆','Visų laikų geriausios lietuviškos dainos — TOP rinkinys | music.lt','Visų laikų geriausios lietuviškos dainos: nemirštantys hitai per visas kartas. Lietuviškos muzikos aukso fondas viename rinkinyje.','Yra dainų, kurios nepavaldžios laikui. Surinkome visų laikų geriausias lietuviškas dainas — kūrinius, kuriuos žino kelios kartos ir kurie skamba iki šiol. Lietuviškos muzikos aukso fondas: estrada, rokas, popsas ir baladės, tapusios klasika.','tema',14,true),
('90-uju-hitai','song','90-ųjų hitai','📼','90-ųjų hitai — dešimtmečio dainos | music.lt','90-ųjų hitai: dešimtmečio populiariausios dainos. Nostalgiškas lietuviškų ir pasaulio 1990-ųjų kūrinių rinkinys.','Devyniasdešimtieji turėjo savo nepakartojamą garsą. Surinkome ryškiausius 90-ųjų hitus — dainas, kurios skambėjo per radiją, diskotekose ir kasečių grotuvuose. Lietuviški ir pasaulio kūriniai, grąžinantys dešimtmečio nostalgiją.','tema',15,true),
('2000-uju-hitai','song','2000-ųjų hitai','💿','2000-ųjų hitai — dešimtmečio dainos | music.lt','2000-ųjų hitai: dešimtmečio populiariausios dainos. Lietuviškų ir pasaulio 2000-ųjų kūrinių rinkinys.','Dvitūkstantieji subrandino naują muzikos kartą. Šiame rinkinyje — populiariausi 2000-ųjų hitai: dainos, kurios apibrėžė dešimtmetį ir tebeskamba vakarėliuose. Lietuvių ir pasaulio atlikėjų kūriniai vienoje vietoje.','tema',16,true),
('dainos-vaikams','song','Dainos vaikams','🧸','Dainos vaikams — geriausios vaikiškos dainos | music.lt','Geriausios dainos vaikams: linksmos lietuviškos vaikiškos dainos žaidimui ir mokymuisi. Vaikų dainų rinkinys visai šeimai.','Vaikystės dainos lieka atmintyje visam gyvenimui. Surinkome geriausias dainas vaikams — linksmas lietuviškas vaikiškas daineles žaidimui, šokiui ir mokymuisi. Smagus rinkinys darželiui, gimtadieniui ir šeimos vakarams.','tema',17,true),
('linksmos-dainos','song','Linksmos dainos','😄','Linksmos dainos — nuotaiką keliantys hitai | music.lt','Linksmos dainos gerai nuotaikai: energingi kūriniai, kurie pralinksmins ir privers šypsotis. Lietuviškų ir pasaulio hitų rinkinys.','Gera daina gali pakeisti visą dieną. Surinkome linksmiausias dainas, keliančias nuotaiką ir verčiančias šypsotis — energingi lietuviški ir pasaulio kūriniai rytui, kelionei ar tiesiog tada, kai norisi pasidžiaugti.','nuotaika',18,true)
on conflict (kind,slug) do nothing;
