-- 20260614b_collections.sql
-- Kolekciju (song+album) definiciju saugykla. Valdoma per /admin/kolekcijos.
-- Seed is lib/collections.ts (13 song + 7 album). Marsrutai skaito is DB.

create table if not exists public.collections (
  id bigserial primary key,
  slug text not null,
  kind text not null check (kind in ('song','album')),
  title text not null,
  emoji text,
  meta_title text,
  description text,
  intro text,
  grp text,
  genre_name text,
  scope text,
  substyle_slug text,
  sort int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (kind, slug)
);
create index if not exists idx_collections_kind_active on public.collections (kind, is_active, sort);
alter table public.collections enable row level security;
drop policy if exists collections_public_read on public.collections;
create policy collections_public_read on public.collections for select using (true);

insert into public.collections (slug,kind,title,emoji,meta_title,description,intro,grp,genre_name,scope,substyle_slug,sort,is_active) values
('meiles-dainos','song','Dainos apie meilę','❤️','Dainos apie meilę — gražiausios meilės dainos | music.lt','Gražiausios dainos apie meilę — lietuviškos ir užsienio. Romantiškų dainų rinkinys vestuvėms, pasimatymui ar tiesiog nuotaikai.','Meilė — labiausiai apdainuojama tema muzikos istorijoje. Šiame rinkinyje surinkome gražiausias dainas apie meilę: nuo švelnių baladžių iki aistringų himnų, lietuvių ir pasaulio atlikėjų. Tinka romantiškam vakarui, pirmam šokiui ar dovanai mylimam žmogui.','tema',null,null,null,0,true),
('vestuviu-dainos','song','Vestuvių dainos','💍','Vestuvių dainos — geriausios dainos vestuvėms | music.lt','Geriausios vestuvių dainos: pirmam šokiui, ceremonijai ir vakarėliui. Lietuviškų ir užsienio dainų rinkinys jūsų didžiajai dienai.','Tinkama daina gali tapti vestuvių akimirkos siela. Surinkome dainas pirmam jaunavedžių šokiui, ceremonijai ir linksmam vakarėliui — nuo jautrių baladžių iki energingų hitų, kurie pakels visus svečius. Lietuviški ir pasaulio kūriniai vienoje vietoje.','tema',null,null,null,1,true),
('filmu-dainos','song','Filmų ir serialų dainos','🎬','Filmų ir serialų dainos — garso takeliai | music.lt','Žinomiausios dainos iš filmų ir serialų. Garso takelių ir kino muzikos rinkinys, kurį atpažins kiekvienas.','Kai kurios dainos neatsiejamos nuo scenų, kuriose nuskambėjo. Šiame rinkinyje — įsimintiniausios filmų ir serialų dainos bei garso takeliai, kurie tapo populiaresni už pačius filmus. Kino muzikos klasika ir naujausi hitai iš ekrano.','tema',null,null,null,2,true),
('lopsines','song','Lopšinės','🌙','Lopšinės — ramios dainos vaikams užmigti | music.lt','Gražiausios lopšinės vaikams: ramios lietuviškos ir pasaulio dainos miegui. Švelnios melodijos vakaro ritualui.','Lopšinė — pirmoji muzika, kurią išgirstame gyvenime. Surinkome ramiausias lietuviškas ir pasaulio lopšines, padedančias mažyliams nurimti ir užmigti. Švelnios melodijos vakaro ritualui visai šeimai.','tema',null,null,null,3,true),
('lietuviskos-klasikes','song','Lietuviškos klasikės','🇱🇹','Lietuviškos klasikės — nemirštantys hitai | music.lt','Nemirštantys lietuviški hitai, kuriuos žino visi. Lietuviškos estrados ir roko klasikos dainų rinkinys per kartas.','Yra dainų, kurias moka kiekvienas lietuvis. Šiame rinkinyje — auksinis lietuviškos muzikos fondas: estrados, roko ir poso klasika, skambanti vestuvėse, gimtadieniuose ir prie laužo jau ne vieną kartą. Dainos, kurias perduodame iš kartos į kartą.','tema',null,null,null,4,true),
('vasaros-hitai-2026','song','Vasaros hitai 2026','☀️','Vasaros hitai 2026 — karščiausios vasaros dainos | music.lt','2026 metų vasaros hitai: karščiausios dainos paplūdimiui, kelionei ir vakarėliui. Šio sezono populiariausi kūriniai.','Kiekviena vasara turi savo garso takelį. Surinkome 2026 metų vasaros hitus — energingiausias šio sezono dainas paplūdimiui, automobiliui ir naktiniam vakarėliui. Lietuvių ir pasaulio atlikėjų kūriniai, skambantys visur šią vasarą.','tema',null,null,null,5,true),
('protestas-ir-laisve','song','Protestas ir laisvė','✊','Protesto ir laisvės dainos — kovos himnai | music.lt','Protesto ir laisvės dainos: kovos himnai, dainuojanti revoliucija ir laisvės balsas muzikoje. Lietuviški ir pasaulio kūriniai.','Muzika visada buvo laisvės balsas. Šiame rinkinyje — dainos, virtusios protesto himnais ir kovos už laisvę simboliais: nuo Dainuojančios revoliucijos kūrinių iki pasaulinių laisvės himnų. Dainos, suvienijusios žmones lemtingomis akimirkomis.','tema',null,null,null,6,true),
('kalediniu-muzika','song','Kalėdinės dainos','🎄','Kalėdinės dainos — geriausia šventinė muzika | music.lt','Geriausios kalėdinės dainos: lietuviškos ir pasaulio šventinės klasikos rinkinys Kūčioms ir Kalėdoms.','Kalėdų nuotaiką sukuria muzika. Surinkome jaukiausias kalėdines dainas — nuo lietuviškų giesmių iki pasaulinės šventinės klasikos, skambančios prie eglutės ir Kūčių stalo. Šventinis rinkinys visai šeimai gruodžio vakarams.','tema',null,null,null,7,true),
('chill','song','Chill nuotaikos','🧊','Chill muzika — ramios dainos atsipalaidavimui | music.lt','Chill muzika atsipalaidavimui: ramios dainos darbui, mokslams ar poilsiui. Raminančių kūrinių rinkinys fonui.','Kartais reikia tiesiog sulėtinti tempą. Šiame rinkinyje — ramios, chill nuotaikos dainos, tinkančios fonui dirbant, mokantis ar tiesiog ilsintis. Švelnūs bitai ir raminančios melodijos be skubėjimo.','nuotaika',null,null,null,8,true),
('workout','song','Workout dainos','💪','Workout muzika — energingos dainos treniruotei | music.lt','Workout muzika treniruotei: energingos dainos bėgimui ir sporto salei. Greito ritmo kūrinių rinkinys motyvacijai.','Tinkamas ritmas gali padvigubinti treniruotės jėgą. Surinkome energingiausias workout dainas bėgimui, sporto salei ir kardio treniruotėms — greito tempo kūrinius, kurie nukels motyvaciją į kitą lygį. Pumpuok garsą ir spausk toliau.','nuotaika',null,null,null,9,true),
('keliones-dainos','song','Kelionės dainos','🚗','Kelionės dainos — geriausia muzika kelionei automobiliu | music.lt','Geriausios kelionės dainos: muzika ilgam ratui automobiliu. Road trip dainų rinkinys, su kuriuo neprailgs kelias.','Ilga kelionė be muzikos — pusė kelionės. Surinkome geriausias road trip dainas, su kuriomis neprailgs net ilgiausias ratas automobiliu. Dainuok kartu, atidaryk langą ir leiskis į kelią.','nuotaika',null,null,null,10,true),
('vakareliu-muzika','song','Vakarėlių muzika','🎉','Vakarėlių muzika — geriausios party dainos | music.lt','Vakarėlių muzika: karščiausios party dainos, kurios pakels visus šokti. Lietuviškų ir užsienio hitų rinkinys vakarėliui.','Geras vakarėlis prasideda nuo gero grojaraščio. Surinkome dainas, kurios garantuotai užpildys šokių aikštelę — nuo lietuviškų hitų iki pasaulinių party himnų. Pasukk garsą ir tegul prasideda vakarėlis.','nuotaika',null,null,null,11,true),
('liudnos-dainos','song','Liūdnos dainos','😢','Liūdnos dainos — gražiausios graudžios baladės | music.lt','Gražiausios liūdnos dainos: graudžios baladės sunkiai akimirkai. Melancholiškų kūrinių rinkinys, kai reikia išsiverkti.','Kartais liūdna daina paguodžia geriau nei žodžiai. Šiame rinkinyje — gražiausios liūdnos baladės ir melancholiški kūriniai sunkiai akimirkai. Muzika, kuri supranta, leidžia pajausti ir pamažu paleisti.','nuotaika',null,null,null,12,true),
('roko','album','Geriausi roko albumai','🎸','Geriausi roko albumai — roko klasika ir naujienos | music.lt','Geriausi roko albumai music.lt kataloge: legendinė roko klasika ir naujausi išleidimai. Lietuvių ir pasaulio roko grupių diskografijos.','Rokas — žanras, apibrėžęs ištisas kartas. Surinkome reikšmingiausius roko albumus: nuo nemirštančios klasikos iki šviežiausių išleidimų. Lietuvių ir pasaulio grupių darbai, kuriuos verta išgirsti nuo pradžios iki pabaigos.',null,'Roko muzika',null,null,0,true),
('pop','album','Geriausi pop albumai','🎤','Geriausi pop albumai — populiariausi pop ir R&B albumai | music.lt','Geriausi pop ir R&B albumai: populiariausių atlikėjų darbai vienoje vietoje. Lietuviška ir pasaulio popmuzika.','Popmuzika diktuoja, ką dainuoja visas pasaulis. Šiame rinkinyje — ryškiausi pop ir R&B albumai, formuojantys šiandienos garsą. Lietuvių ir pasaulio žvaigždžių darbai, kuriuos žino kiekvienas.',null,'Pop, R&B muzika',null,null,1,true),
('lietuviski','album','Geriausi lietuviški albumai','🇱🇹','Geriausi lietuviški albumai — LT muzikos fondas | music.lt','Geriausi lietuviški albumai: nacionalinės muzikos fondas nuo klasikos iki šiandienos. Populiariausių Lietuvos atlikėjų darbai.','Lietuviška muzika turi savo aukso fondą. Surinkome reikšmingiausius lietuviškus albumus — nuo legendinių estrados ir roko darbų iki naujosios scenos išleidimų. Nacionalinės muzikos istorija viename rinkinyje.',null,null,'lt',null,2,true),
('hip-hop','album','Geriausi hip-hop albumai','🎧','Geriausi hip-hop albumai — repo klasika ir naujienos | music.lt','Geriausi hip-hop ir repo albumai: lietuviška ir pasaulio gatvės muzika. Reikšmingiausi žanro darbai vienoje vietoje.','Hip-hopas — daugiau nei muzika, tai kultūra ir balsas. Šiame rinkinyje — svarbiausi hip-hop ir repo albumai: lietuvių scenos darbai ir pasaulio klasika, apibrėžę žanrą ir gatvės garsą.',null,'Hip-hop''o muzika',null,null,3,true),
('metalo','album','Geriausi metalo albumai','🤘','Geriausi metalo albumai — sunkiosios muzikos klasika | music.lt','Geriausi metalo ir sunkiosios muzikos albumai: nuo klasikinio heavy metal iki modernių žanrų. Lietuvių ir pasaulio grupės.','Metalas — vienas galingiausių muzikos žanrų. Surinkome sunkiausius ir reikšmingiausius metalo albumus: nuo klasikinio heavy metal iki ekstremalesnių atšakų. Lietuvių ir pasaulio grupių darbai gerbėjams.',null,'Sunkioji muzika',null,null,4,true),
('jazz','album','Geriausi džiazo albumai','🎷','Geriausi džiazo albumai — jazz klasika ir naujienos | music.lt','Geriausi džiazo albumai: jazz klasika ir šiuolaikiniai darbai. Improvizacijos ir grūvio meistrų rinkinys.','Džiazas — laisvės ir improvizacijos muzika. Šiame rinkinyje — reikšmingiausi jazz albumai nuo klasikinių įrašų iki šiuolaikinių interpretacijų. Subtilus grūvis ir meistriškumas tiems, kas vertina gilumą.',null,null,null,'jazz',5,true),
('elektronines','album','Geriausi elektroniniai albumai','🎛️','Geriausi elektroniniai albumai — EDM ir šokių muzika | music.lt','Geriausi elektroniniai ir šokių muzikos albumai: nuo techno iki house. Lietuvių ir pasaulio elektroninės scenos darbai.','Elektroninė muzika nutiesė kelią į ateities garsą. Surinkome ryškiausius elektroninius ir šokių muzikos albumus — nuo techno ir house iki eksperimentinių darbų. Lietuvių ir pasaulio prodiuserių kūriniai šokių aikštelei ir klausymuisi.',null,'Elektroninė, šokių muzika',null,null,6,true)
on conflict (kind,slug) do nothing;
